apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr-agents.labels" . | nindent 4 }}
data:
  localRegistryHosting.v1: |
    host: "localhost:5001"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
